### ISSUE TITLE
[feature request] Increase internal res

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/libretro-vecx#11]
I played around with this some but never got it to work quite right, so I figured I'd post about it here.

If you increase the width, height and bufsz, you can get a higher internal resolution, which makes for smoother lines but it also messes up the "stride" or whatever (that is, it makes the lines diagonal and they point off the screen).

**Comment by Enverex** [comment]
Ditto on this. The vectrex was vector based (hence the name) which made lines look nice and smooth regardless of the angle. Because this renders at such low resolution, all lines look terrible (using a scaler helps a bit, but is far from properly smoothed).

**Comment by mudlord** [comment]
Now this is done proper AA based line drawing needs to be done. Xiolin Wu would be nice or some other alpha based line drawing which takes into account subpixels.

**Comment by Enverex** [comment]
Just for anyone else arriving here, this issue has been resolved with commit https://github.com/libretro/libretro-vecx/commit/c792d80124e20602987492c9201fee29f63fdaad

**Comment by Enverex** [comment]
This isn't working quite right. Changing the value in the config works, but it doesn't apply it the next time RetroArch is opened BUT, the option IS remembered in the menu settings.

Clarification: If you go and set it to 4x, it works as expected. If you quit RetroArch then go back in, the menu will still say it's at 4x, but it'll clearly be at 1x. Going back into the menu, changing it to something else then back to the desired value corrects it again (until you restart RetroArch).

**Comment by hizzlekizzle** [comment]
I put in a PR to correct that behavior:
https://github.com/libretro/libretro-vecx/pull/15

**Comment by gouchi** [comment]
@Enverex @hizzlekizzle This issue can be closes as the latest PR has been merged ?

Thank you.

**Comment by hizzlekizzle** [comment]
Yes, I actually fixed this myself ages ago but never closed it back then. May as well do it now :P
