### ISSUE TITLE
platform detection breaks on linux if hostname contains "win"

### ISSUE THREAD

**Issue by joolswills** [libretro/libretro-vecx#19]
This affects a bunch of cores due to makefile code like

```
ifeq ($(platform),)
platform = unix
ifeq ($(shell uname -a),)
   platform = win
else ifneq ($(findstring MINGW,$(shell uname -a)),)
   platform = win
else ifneq ($(findstring Darwin,$(shell uname -a)),)
   platform = osx
   arch = intel
ifeq ($(shell uname -p),powerpc)
   arch = ppc
endif
else ifneq ($(findstring win,$(shell uname -a)),)
   platform = win
endif
endif
```

if the hostname on a linux system contains the word `win` at all, the detection will fail. I suspect using something like `uname -s` would be more appropriate for matching against `MINGW` or `win`.

**Comment by joolswills** [comment]
These cores may also be affected (and possibly others - this list os from a RetroPie user who had some failed builds due to this issue).

```
lr-atari800
lr-beetle-ngp
lr-caprice32
lr-fceumm
lr-fuse
lr-genesis-plus-gx
lr-handy
lr-mame2000
lr-mame2003
lr-nestopia
lr-picodrive
lr-quicknes
lr-snes9x2010
lr-vba-next
lr-vecx
```

**Comment by endrift** [comment]
This was fixed in the mgba port in https://github.com/libretro/mgba/commit/337fc06385f08ef610f3425cb6c16bac14064192 -- I pointed out at that time that many cores were affected by this, but I never built a list.
