### ISSUE TITLE
Why the weird point shape?

### ISSUE THREAD

**Issue by arpruss** [libretro/libretro-vecx#34]
I noticed that points on the screen were weirdly triangular, and then looked at the code. At resolution multipliers 2 and 3 which have a point size of 2, the points drawn have this shape:
```
XXX
XX.
X..
```
and at multiplier 4 which has the point size of 3, they have the shape:
```
XXXX
XXX.
XX..
X...
```

Is there a reason why they have these weird shapes? It seems to me that this will result in lines (which are currently drawn with points) having rather different thickness depending on their slope, and the points that text (e.g., scores) are drawn with look weird being made of little triangles. It seems to me that it would look better to use shapes like:
Size 2 (multipliers 2-3):
```
.X.
XXX
.X.
```
Size 3 (multiplier 4):
```
.XX.
XXXX
XXXX
.XX.
```

**Comment by hizzlekizzle** [comment]
The res-multiplication code is very naive. If you have a better method, I'm all for it :)

**Comment by arpruss** [comment]
What would be really nice is to have antialiased lines, but I worry that that will be too slow on some devices. In the meanwhile, I'll submit a PR with the shape tweaks indicated above.

**Comment by grolliffe** [comment]
Just in case you're thinking of investigating anti-aliased lines, you might want to check [Rendering vector games on low end GPUs](https://forums.libretro.com/t/rendering-vector-games-on-low-end-gpus/27787).

**Comment by hizzlekizzle** [comment]
Yeah, IIRC we're using a basic [Bresenham](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm) algo to draw the lines but something like [Xiaolin Wu](https://en.wikipedia.org/wiki/Xiaolin_Wu%27s_line_algorithm) should look a lot nicer.

**Comment by arpruss** [comment]
For single thickness that would work well. But for thicker lines it gets tricky.
