### ISSUE TITLE
[Feature Request] Core for Wii

### ISSUE THREAD

**Issue by Edu789** [libretro/libretro-vecx#38]
Hi there, just wondering why this core is not available on Retroarch for Wii. Any chance it could be made to work on the Wii? Thanks.

**Comment by twinaphex** [comment]
Added it for Gamecube and Wii now -

https://github.com/libretro/libretro-vecx/commit/0f3f04b0e5bbb484a84e3416d07f0ae8cdac386e

Hope it works in tomorrow's nightlies.

**Comment by twinaphex** [comment]
@Edu789 Can you tell me if this works now?

**Comment by Edu789** [comment]
It's working perfectly, thanks.
