### ISSUE TITLE
[Bug] Berzerk sound bug

### ISSUE THREAD

**Issue by QcSamuel** [libretro/libretro-vecx#52]
there a constant buzzing/noise on Berzerk with this core tried the game on mame and it doesnt have this issue so its not a normal thing in the game

**Comment by hizzlekizzle** [comment]
Can you try the build from here? https://github.com/hunterk/libretro-vecx/releases

**Comment by QcSamuel** [comment]
> Can you try the build from here? https://github.com/hunterk/libretro-vecx/releases

forgot to say i use retroarch on ios but i can try the build from there on my pc when im home

**Comment by QcSamuel** [comment]
@hizzlekizzle same sound problem with that one

**Comment by hizzlekizzle** [comment]
ok, that one has some accuracy improvements, so if it's not fixed there, either, it might be a deeper issue that doesn't have an easy fix.

**Comment by QcSamuel** [comment]
thank you :)
